apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
  creationTimestamp: null
  labels:
    app: aws-example-octodex
  name: aws-example-octodex
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: aws-example-octodex
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aws-example-octodex
    spec:
      containers:
      - image: 768153225182.dkr.ecr.ap-south-1.amazonaws.com/example-eks:21bf7007e2dd0c64f0de9c5bd6594bc01909d6df
        imagePullPolicy: IfNotPresent
        name: aws-example-octodex
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
